name: C CI

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev

      - name: Build (gcc)
        run: |
          gcc -std=c11 \
              -Wall -Wextra -Werror \
              -O2 \
              src/*.c \
              -Iinclude \
              -lssl -lcrypto \
              -o vault

      - name: Build (clang)
        run: |
          clang -std=c11 \
                -Wall -Wextra -Werror \
                -O2 \
                src/*.c \
                -Iinclude \
                -lssl -lcrypto \
                -o vault-clang
